# Uncomment the next line to define a global platform for your project

platform :ios, '10.0' 
swift_version = '5.0' 
use_frameworks! inhibit_all_warnings!


target 'my_english_app' do
 pod 'RxCocoa'
 pod 'Alamofire'
 pod 'SwiftyJSON'
 pod 'Kingfisher'
 pod 'EmptyDataSet-Swift'
end
